"""Closed vocabularies used across the engine. Strings are stable wire values."""

from __future__ import annotations

from enum import Enum


class SourceSystem(str, Enum):
    ORDERS = "ORDERS"
    SETTLEMENTS = "SETTLEMENTS"
    BANK = "BANK"
    INVOICES = "INVOICES"


class TransactionType(str, Enum):
    ORDER_PAYMENT = "ORDER_PAYMENT"
    SETTLEMENT_PAYOUT = "SETTLEMENT_PAYOUT"
    BANK_CREDIT = "BANK_CREDIT"
    BANK_DEBIT = "BANK_DEBIT"
    INVOICE = "INVOICE"


class ReconciliationStatus(str, Enum):
    MATCHED = "MATCHED"
    PARTIAL_MATCH = "PARTIAL_MATCH"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    EXCEPTION = "EXCEPTION"
    DUPLICATE = "DUPLICATE"
    UNRESOLVED = "UNRESOLVED"


#: Statuses that are counted as a clean deterministic match in the match rate.
MATCHED_STATUSES = frozenset({ReconciliationStatus.MATCHED})

#: Statuses that leave money unexplained and must be surfaced to a human.
RESIDUAL_STATUSES = frozenset(
    {
        ReconciliationStatus.REVIEW_REQUIRED,
        ReconciliationStatus.EXCEPTION,
        ReconciliationStatus.DUPLICATE,
        ReconciliationStatus.UNRESOLVED,
    }
)

EXCEPTION_STATUSES = frozenset(
    {ReconciliationStatus.EXCEPTION, ReconciliationStatus.UNRESOLVED}
)


class MatchType(str, Enum):
    """How the match was established. Ordered from strongest to weakest."""

    EXACT_PAYMENT_ID = "EXACT_PAYMENT_ID"
    EXACT_SETTLEMENT_ID = "EXACT_SETTLEMENT_ID"
    EXACT_INVOICE_ID = "EXACT_INVOICE_ID"
    EXACT_BANK_REFERENCE = "EXACT_BANK_REFERENCE"
    ACCOUNTING_INVARIANT = "ACCOUNTING_INVARIANT"
    AGGREGATED_SETTLEMENT = "AGGREGATED_SETTLEMENT"
    SPLIT_SETTLEMENT = "SPLIT_SETTLEMENT"
    NETTED_ADJUSTMENT = "NETTED_ADJUSTMENT"
    AMOUNT_DATE_WINDOW = "AMOUNT_DATE_WINDOW"
    REFERENCE_PREFIX = "REFERENCE_PREFIX"
    NONE = "NONE"


class ConfidenceMethod(str, Enum):
    """Every confidence number must name the deterministic rule that produced it."""

    EXACT_IDENTIFIER = "EXACT_IDENTIFIER"
    ACCOUNTING_INVARIANT = "ACCOUNTING_INVARIANT"
    ACCOUNTING_INVARIANT_WITHIN_ROUNDING_TOLERANCE = (
        "ACCOUNTING_INVARIANT_WITHIN_ROUNDING_TOLERANCE"
    )
    AGGREGATED_INVARIANT = "AGGREGATED_INVARIANT"
    REFERENCE_EXTRACTION_EXACT = "REFERENCE_EXTRACTION_EXACT"
    REFERENCE_PREFIX_UNIQUE = "REFERENCE_PREFIX_UNIQUE"
    AMOUNT_DATE_COUNTERPARTY_COMPOSITE = "AMOUNT_DATE_COUNTERPARTY_COMPOSITE"
    NOT_ESTABLISHED = "NOT_ESTABLISHED"


class ReasonCode(str, Enum):
    """Machine-readable explanation attached to a reconciliation result.

    A residual result MUST carry at least one reason code. The engine never
    returns an unexplained outcome.
    """

    MISSING_SETTLEMENT = "MISSING_SETTLEMENT"
    DUPLICATE_SETTLEMENT = "DUPLICATE_SETTLEMENT"
    MISSING_BANK_TRANSACTION = "MISSING_BANK_TRANSACTION"
    DUPLICATE_BANK_TRANSACTION = "DUPLICATE_BANK_TRANSACTION"
    UNKNOWN_BANK_CREDIT = "UNKNOWN_BANK_CREDIT"
    UNRECOGNISED_REFERENCE_FORMAT = "UNRECOGNISED_REFERENCE_FORMAT"
    ROUNDING_TOLERANCE_APPLIED = "ROUNDING_TOLERANCE_APPLIED"
    NET_AMOUNT_VARIANCE = "NET_AMOUNT_VARIANCE"
    GATEWAY_FEE_MISMATCH = "GATEWAY_FEE_MISMATCH"
    GST_MISMATCH = "GST_MISMATCH"
    TDS_MISMATCH = "TDS_MISMATCH"
    REFUND_NETTED = "REFUND_NETTED"
    PARTIAL_REFUND = "PARTIAL_REFUND"
    CHARGEBACK = "CHARGEBACK"
    AGGREGATED_SETTLEMENT = "AGGREGATED_SETTLEMENT"
    SPLIT_SETTLEMENT = "SPLIT_SETTLEMENT"
    DELAYED_SETTLEMENT = "DELAYED_SETTLEMENT"
    TRUNCATED_BANK_REFERENCE = "TRUNCATED_BANK_REFERENCE"
    BANK_REFERENCE_NORMALIZED = "BANK_REFERENCE_NORMALIZED"
    PROMOTED_RULE_APPLIED = "PROMOTED_RULE_APPLIED"
    COUNTERPARTY_ALIAS_RESOLVED = "COUNTERPARTY_ALIAS_RESOLVED"
    DATE_FORMAT_NORMALIZED = "DATE_FORMAT_NORMALIZED"
    INVOICE_LINK_BROKEN = "INVOICE_LINK_BROKEN"
    INVOICE_TYPO_RESOLVED = "INVOICE_TYPO_RESOLVED"
    BANK_AMOUNT_VARIANCE = "BANK_AMOUNT_VARIANCE"
    OUTSIDE_DATE_TOLERANCE = "OUTSIDE_DATE_TOLERANCE"


class AdjustmentType(str, Enum):
    REFUND_NETTING = "REFUND_NETTING"
    PARTIAL_REFUND = "PARTIAL_REFUND"
    CHARGEBACK = "CHARGEBACK"
    FEE_CORRECTION = "FEE_CORRECTION"
    TAX_CORRECTION = "TAX_CORRECTION"


class AuditAction(str, Enum):
    RUN_STARTED = "RUN_STARTED"
    RUN_COMPLETED = "RUN_COMPLETED"
    DATA_INGESTED = "DATA_INGESTED"
    RECORD_NORMALIZED = "RECORD_NORMALIZED"
    RECONCILIATION_MATCH = "RECONCILIATION_MATCH"
    RECONCILIATION_PARTIAL = "RECONCILIATION_PARTIAL"
    RECONCILIATION_EXCEPTION = "RECONCILIATION_EXCEPTION"
    RECONCILIATION_DUPLICATE = "RECONCILIATION_DUPLICATE"
    ADJUSTMENT_RECORDED = "ADJUSTMENT_RECORDED"
    INVARIANT_VERIFIED = "INVARIANT_VERIFIED"
    INVARIANT_VIOLATED = "INVARIANT_VIOLATED"
    ARBITRATION_REQUESTED = "ARBITRATION_REQUESTED"
    ARBITRATION_SKIPPED = "ARBITRATION_SKIPPED"
    RULE_PROPOSED = "RULE_PROPOSED"
    RULE_STATUS_CHANGED = "RULE_STATUS_CHANGED"


class ArbitrationDecision(str, Enum):
    RESOLVE = "RESOLVE"
    PROBABLE = "PROBABLE"
    UNRESOLVED = "UNRESOLVED"


class RuleStatus(str, Enum):
    PROPOSED = "PROPOSED"
    VALIDATING = "VALIDATING"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    RETIRED = "RETIRED"


class RuleType(str, Enum):
    NORMALIZATION = "NORMALIZATION"
    MATCHING = "MATCHING"
    ACCOUNTING = "ACCOUNTING"
    CLASSIFICATION = "CLASSIFICATION"


class JournalEntryStatus(str, Enum):
    DRAFT = "DRAFT"
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    POSTED = "POSTED"
    REJECTED = "REJECTED"


class AnomalyType(str, Enum):
    """Ground-truth labels produced by the synthetic generator.

    These are NEVER surfaced in the operator-facing reconciliation UI. They
    exist solely so precision/recall can be measured against a known truth.
    """

    MISSING_SETTLEMENT = "MISSING_SETTLEMENT"
    DUPLICATE_SETTLEMENT = "DUPLICATE_SETTLEMENT"
    MISSING_BANK_TRANSACTION = "MISSING_BANK_TRANSACTION"
    DUPLICATE_BANK_TRANSACTION = "DUPLICATE_BANK_TRANSACTION"
    INVOICE_TYPO = "INVOICE_TYPO"
    CUSTOMER_NAME_ALIAS = "CUSTOMER_NAME_ALIAS"
    DATE_FORMAT_DIFFERENCE = "DATE_FORMAT_DIFFERENCE"
    ROUNDING_ERROR = "ROUNDING_ERROR"
    PARTIAL_REFUND = "PARTIAL_REFUND"
    NETTED_REFUND = "NETTED_REFUND"
    AGGREGATED_SETTLEMENT = "AGGREGATED_SETTLEMENT"
    SPLIT_SETTLEMENT = "SPLIT_SETTLEMENT"
    DELAYED_SETTLEMENT = "DELAYED_SETTLEMENT"
    CHARGEBACK = "CHARGEBACK"
    TDS_DISCREPANCY = "TDS_DISCREPANCY"
    GST_DISCREPANCY = "GST_DISCREPANCY"
    TRUNCATED_BANK_REFERENCE = "TRUNCATED_BANK_REFERENCE"
    UNKNOWN_BANK_CREDIT = "UNKNOWN_BANK_CREDIT"
    UNRECOGNISED_REFERENCE_FORMAT = "UNRECOGNISED_REFERENCE_FORMAT"
